[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx prisma migrate deploy",
  "node prisma/seed.js"
]

[start]
cmd = "node src/server.js"
